In [17]:
# Importing Libraries

import sqlite3 as sql3
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
conn = sql3.connect('expense_tracker.db')

In [3]:
cursor = conn.cursor()

In [4]:
file = '/Users/shivammishra/Downloads/expenses.csv'
df = pd.read_csv(file)
df

,hrk,vendor,date,description,meansofpayment,city,category,currency,country,lcy,...,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27
0,60.96,waw-airport,19.09.2018.,food,cash,warszaw,groceries,PLN,poland,8.16,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,420.00,dorm,20.09.2018.,accomodation,cash,poznan,accomodation,PLN,poland,239.40,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,660.00,dorm,20.09.2018.,accomodation,cash,poznan,accomodation,PLN,poland,376.20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,13.99,bistro,21.09.2018.,food,cash,poznan,groceries,PLN,poland,7.97,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,14.89,biedronka,21.09.2018.,food,cash,poznan,groceries,PLN,poland,8.49,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
165,10.00,konzum,24.12.,food,credit-card,zagreb,groceries,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
166,100.00,ina,27.12.,gas,cash,zagreb,car,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
167,120.00,ice-skating,27.12.,ice-skating,cash,zagreb,activities,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
168,200.00,ina,27.12.,gas,cash,zagreb,car,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
169,12.00,coffee-shop,06.01.2019.,coffee,cash,zagreb,activities,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 170 entries, 0 to 169
Data columns (total 28 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   hrk             161 non-null    float64
 1   vendor          170 non-null    object
 2   date            170 non-null    object
 3   description     170 non-null    object
 4   meansofpayment  170 non-null    object
 5   city            170 non-null    object
 6   category        170 non-null    object
 7   currency        76 non-null     object
 8   country         81 non-null     object
 9   lcy             85 non-null     float64
 10  eur             85 non-null     float64
 11  tags            63 non-null     object
 12  recurrence      76 non-null     object
 13  Unnamed: 13     0 non-null      float64
 14  Unnamed: 14     0 non-null      float64
 15  Unnamed: 15     0 non-null      float64
 16  Unnamed: 16     0 non-null      float64
 17  Unnamed: 17     0 non-null      float64
 18  Unnamed: 18     0 non-null      float64
 19  Unnamed: 19     0 non-null      float64
 20  Unnamed: 20     0 non-null      float64
 21  Unnamed: 21     0 non-null      float64
 22  Unnamed: 22     0 non-null      float64
 23  Unnamed: 23     0 non-null      float64
 24  Unnamed: 24     0 non-null      float64
 25  Unnamed: 25     0 non-null      float64
 26  Unnamed: 26     0 non-null      float64
 27  Unnamed: 27     0 non-null      float64
dtypes: float64(18), object(10)
memory usage: 37.3+ KB

In [11]:
df.isnull().sum()

hrk                 9
vendor              0
date                0
description         0
meansofpayment      0
city                0
category            0
currency           94
country            89
lcy                85
eur                85
tags              107
recurrence         94
Unnamed: 13       170
Unnamed: 14       170
Unnamed: 15       170
Unnamed: 16       170
Unnamed: 17       170
Unnamed: 18       170
Unnamed: 19       170
Unnamed: 20       170
Unnamed: 21       170
Unnamed: 22       170
Unnamed: 23       170
Unnamed: 24       170
Unnamed: 25       170
Unnamed: 26       170
Unnamed: 27       170
dtype: int64

In [5]:
# ignoring the null values
attributes = ['hrk','vendor', 'date', 'description','meansofpayment','city', 'category', 'currency','country']
new_data = df[attributes]

In [8]:
new_data.rename(columns={'hrk': 'cost'}, inplace=True)
new_data

/var/folders/y0/5l57ym2573553zlkd56cz9w80000gn/T/ipykernel_36046/4007409240.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_data.rename(columns={'hrk': 'cost'}, inplace=True)

,cost,vendor,date,description,meansofpayment,city,category,currency,country
0,60.96,waw-airport,19.09.2018.,food,cash,warszaw,groceries,PLN,poland
1,420.00,dorm,20.09.2018.,accomodation,cash,poznan,accomodation,PLN,poland
2,660.00,dorm,20.09.2018.,accomodation,cash,poznan,accomodation,PLN,poland
3,13.99,bistro,21.09.2018.,food,cash,poznan,groceries,PLN,poland
4,14.89,biedronka,21.09.2018.,food,cash,poznan,groceries,PLN,poland
...,...,...,...,...,...,...,...,...,...
165,10.00,konzum,24.12.,food,credit-card,zagreb,groceries,NaN,NaN
166,100.00,ina,27.12.,gas,cash,zagreb,car,NaN,NaN
167,120.00,ice-skating,27.12.,ice-skating,cash,zagreb,activities,NaN,NaN
168,200.00,ina,27.12.,gas,cash,zagreb,car,NaN,NaN
169,12.00,coffee-shop,06.01.2019.,coffee,cash,zagreb,activities,NaN,NaN

In [9]:
# Creating the table 
sql_qry = """
create table expense(
id serial,
cost int not null,
vendor text,
date datetime,
meansofpayment text,
city varchar(50),
category varchar(10),
currency varchar(5),
counrty varchar(20)
)
"""

cursor.execute(sql_qry)

In [12]:
# Inserting the data

new_data.to_sql('expense', conn, index=False, if_exists='replace')

170

In [14]:
res = cursor.execute('select * from expense')

In [15]:
res.fetchall()

[(60.96,
  'waw-airport',
  '19.09.2018.',
  'food',
  'cash',
  'warszaw',
  'groceries',
  'PLN',
  'poland'),
 (420.0,
  'dorm',
  '20.09.2018.',
  'accomodation',
  'cash',
  'poznan',
  'accomodation',
  'PLN',
  'poland'),
 (660.0,
  'dorm',
  '20.09.2018.',
  'accomodation',
  'cash',
  'poznan',
  'accomodation',
  'PLN',
  'poland'),
 (13.99,
  'bistro',
  '21.09.2018.',
  'food',
  'cash',
  'poznan',
  'groceries',
  'PLN',
  'poland'),
 (14.89,
  'biedronka',
  '21.09.2018.',
  'food',
  'cash',
  'poznan',
  'groceries',
  'PLN',
  'poland'),
 (138.42,
  'carrefour',
  '21.09.2018.',
  'food',
  'cash',
  'poznan',
  'groceries',
  'PLN',
  'poland'),
 (17.3,
  'nowe-zoo',
  '21.09.2018.',
  'activity',
  'cash',
  'poznan',
  'activities',
  'PLN',
  'poland'),
 (10.38,
  'malta-train',
  '21.09.2018.',
  'train',
  'cash',
  'poznan',
  'transport',
  'PLN',
  'poland'),
 (177.87,
  'carrefour',
  '22.09.2018.',
  'supplies',
  'cash',
  'poznan',
  'groceries',
  'PLN',
  'poland'),
 (17.21,
  'starbucks',
  '22.09.2018.',
  'food',
  'cash',
  'poznan',
  'groceries',
  'PLN',
  'poland'),
 (15.93,
  'carrefour',
  '22.09.2018.',
  'food',
  'cash',
  'poznan',
  'groceries',
  'PLN',
  'poland'),
 (34.8,
  'bar',
  '22.09.2018.',
  'alcohol',
  'cash',
  'poznan',
  'activities',
  'PLN',
  'poland'),
 (35.04,
  'biedronka',
  '24.09.2018.',
  'food',
  'cash',
  'poznan',
  'groceries',
  'PLN',
  'poland'),
 (26.0,
  'daniel-prlat',
  '24.09.2018.',
  'food',
  'credit-card',
  'poznan',
  'fastfood',
  'PLN',
  'poland'),
 (69.52,
  'czupito',
  '24.09.2018.',
  'alcohol',
  'cash',
  'poznan',
  'activities',
  'PLN',
  'poland'),
 (38.28,
  'breakfast',
  '25.09.2018.',
  'food',
  'cash',
  'poznan',
  'groceries',
  'PLN',
  'poland'),
 (34.08,
  'museum',
  '25.09.2018.',
  'museum',
  'cash',
  'poznan',
  'sightseeing',
  'PLN',
  'poland'),
 (66.8,
  'rossman',
  '25.09.2018.',
  'supplies',
  'credit-card',
  'poznan',
  'groceries',
  'PLN',
  'poland'),
 (293.52,
  'kiwi',
  '25.09.2018.',
  'airplane',
  'credit-card',
  'poznan',
  'travel',
  'PLN',
  'poland'),
 (11.32,
  'breakfast',
  '26.09.2018.',
  'food',
  'cash',
  'poznan',
  'groceries',
  'PLN',
  'poland'),
 (13.06,
  'public-canteen',
  '26.09.2018.',
  'food',
  'cash',
  'poznan',
  'groceries',
  'PLN',
  'poland'),
 (41.59,
  'biedronka',
  '26.09.2018.',
  'food',
  'credit-card',
  'poznan',
  'groceries',
  'PLN',
  'poland'),
 (72.01,
  'cinema',
  '26.09.2018.',
  'activity',
  'cash',
  'poznan',
  'activities',
  'PLN',
  'poland'),
 (28.05,
  'carrefour',
  '27.09.2018.',
  'food',
  'credit-card',
  'poznan',
  'groceries',
  'PLN',
  'poland'),
 (101.35,
  'carrefour',
  '27.09.2018.',
  'food',
  'credit-card',
  'poznan',
  'groceries',
  'PLN',
  'poland'),
 (260.0,
  'integration-week',
  '28.09.2018.',
  'activity',
  'cash',
  'poznan',
  'activities',
  'PLN',
  'poland'),
 (70.0,
  'esncard',
  '28.09.2018.',
  'esncard',
  'credit-card',
  'poznan',
  'travel',
  'PLN',
  'poland'),
 (2.1,
  'blinkee',
  '29.09.2018.',
  'blinkee',
  'credit-card',
  'poznan',
  'transport',
  'PLN',
  'poland'),
 (17.51,
  'pikapika',
  '29.09.2018.',
  'food',
  'credit-card',
  'poznan',
  'fastfood',
  'PLN',
  'poland'),
 (17.51,
  'pikapika',
  '29.09.2018.',
  'food',
  'credit-card',
  'poznan',
  'fastfood',
  'PLN',
  'poland'),
 (2.62,
  'jakdojade',
  '29.09.2018.',
  'tram',
  'credit-card',
  'poznan',
  'transport',
  'PLN',
  'poland'),
 (154.42,
  'decathlon',
  '29.09.2018.',
  'supplies',
  'credit-card',
  'poznan',
  'groceries',
  'PLN',
  'poland'),
 (17.38,
  'ikea',
  '29.09.2018.',
  'food',
  'cash',
  'poznan',
  'groceries',
  'PLN',
  'poland'),
 (429.26,
  'ikea',
  '29.09.2018.',
  'supplies',
  'credit-card',
  'poznan',
  'groceries',
  'PLN',
  'poland'),
 (13.93,
  'psychodela',
  '01.10.2018.',
  'alcohol',
  'cash',
  'poznan',
  'activities',
  'PLN',
  'poland'),
 (23.35,
  'carrefour',
  '02.10.2018.',
  'food',
  'credit-card',
  'poznan',
  'groceries',
  'PLN',
  'poland'),
 (20.96,
  'gravitacja',
  '02.10.2018.',
  'alcohol',
  'credit-card',
  'poznan',
  'activities',
  'PLN',
  'poland'),
 (2.96,
  'jakdojade',
  '03.10.2018.',
  'tram',
  'credit-card',
  'poznan',
  'transport',
  'PLN',
  'poland'),
 (20.96,
  'welonmucha',
  '03.10.2018.',
  'alcohol',
  'credit-card',
  'poznan',
  'activities',
  'PLN',
  'poland'),
 (15.72,
  'welonmucha',
  '03.10.2018.',
  'alcohol',
  'credit-card',
  'poznan',
  'activities',
  'PLN',
  'poland'),
 (10.7,
  'carrefour',
  '04.10.2018.',
  'food',
  'credit-card',
  'poznan',
  'groceries',
  'PLN',
  'poland'),
 (66.12,
  'newyorker',
  '04.10.2018.',
  'clothes',
  'credit-card',
  'poznan',
  'clothes',
  'PLN',
  'poland'),
 (36.0,
  'uber',
  '05.10.2018.',
  'uber',
  'credit-card',
  'poznan',
  'travel',
  'PLN',
  'poland'),
 (82.58,
  'flygbussarna',
  '05.10.2018.',
  'bus',
  'credit-card',
  'malmo',
  'travel',
  'SEK',
  'sweden'),
 (35.9,
  '7eleven',
  '05.10.2018.',
  'food',
  'credit-card',
  'malmo',
  'fastfood',
  'SEK',
  'sweden'),
 (46.23,
  'coop',
  '05.10.2018.',
  'food',
  'credit-card',
  'malmo',
  'groceries',
  'SEK',
  'sweden'),
 (72.0,
  'malmo-kopenhagen',
  '05.10.2018.',
  'train',
  'credit-card',
  'malmo',
  'travel',
  'SEK',
  'sweden'),
 (170.0,
  'den-blaa-planet',
  '05.10.2018.',
  'aquarium',
  'credit-card',
  'copenhagen',
  'sightseeing',
  'DKK',
  'denmark'),
 (64.25,
  'bilka',
  '05.10.2018.',
  'food',
  'credit-card',
  'copenhagen',
  'groceries',
  'DKK',
  'denmark'),
 (24.0,
  'metro',
  '05.10.2018.',
  'train',
  'credit-card',
  'copenhagen',
  'travel',
  'DKK',
  'denmark'),
 (20.79,
  'coop',
  '06.10.2018.',
  'food',
  'credit-card',
  'copenhagen',
  'groceries',
  'DKK',
  'denmark'),
 (20.0,
  'bastardcafe',
  '06.10.2018.',
  'food',
  'credit-card',
  'copenhagen',
  'fastfood',
  'DKK',
  'denmark'),
 (308.0,
  'copenhagen-gothenburg',
  '06.10.2018.',
  'bus',
  'credit-card',
  'copenhagen',
  'travel',
  'DKK',
  'denmark'),
 (8.0,
  'bus-station',
  '07.10.2018.',
  'coffee',
  'credit-card',
  'gothenburg',
  'fastfood',
  'SEK',
  'sweden'),
 (25.88,
  'lidl',
  '07.10.2018.',
  'food',
  'credit-card',
  'gothenburg',
  'groceries',
  'SEK',
  'sweden'),
 (14.36,
  'pressbyran',
  '07.10.2018.',
  'food',
  'credit-card',
  'gothenburg',
  'groceries',
  'SEK',
  'sweden'),
 (387.0,
  'gothenburg-vasteras',
  '07.10.2018.',
  'bus',
  'credit-card',
  'gothenburg',
  'travel',
  'SEK',
  'sweden'),
 (18.0,
  'ica',
  '08.10.2018.',
  'food',
  'credit-card',
  'vasteras',
  'groceries',
  'SEK',
  'sweden'),
 (144.0,
  'lidl',
  '08.10.2018.',
  'food',
  'credit-card',
  'vasteras',
  'groceries',
  'SEK',
  'sweden'),
 (110.0,
  'prison-island',
  '09.10.2018.',
  'activity',
  'credit-card',
  'vasteras',
  'activities',
  'SEK',
  'sweden'),
 (72.0,
  'cinema',
  '11.10.2018.',
  'activity',
  'credit-card',
  'vasteras',
  'activities',
  'SEK',
  'sweden'),
 (34.0,
  'ica',
  '12.10.2018.',
  'food',
  'credit-card',
  'vasteras',
  'groceries',
  'SEK',
  'sweden'),
 (79.78,
  'vasa',
  '15.10.2018.',
  'museum',
  'credit-card',
  'stockholm',
  'sightseeing',
  'SEK',
  'sweden'),
 (83.0,
  'pizzahut',
  '15.10.2018.',
  'food',
  'credit-card',
  'stockholm',
  'fastfood',
  'SEK',
  'sweden'),
 (104.1,
  'flygbussarna',
  '15.10.2018.',
  'bus',
  'credit-card',
  'stockholm',
  'travel',
  'SEK',
  'sweden'),
 (660.0,
  'dorm',
  '16.10.2018.',
  'accomodation',
  'credit-card',
  'poznan',
  'accomodation',
  'PLN',
  'poland'),
 (34.88,
  'orange',
  '16.10.2018.',
  'internet',
  'credit-card',
  'poznan',
  'unlabeled',
  'PLN',
  'poland'),
 (29.36,
  'biedronka',
  '16.10.2018.',
  'food',
  'credit-card',
  'poznan',
  'groceries',
  'PLN',
  'poland'),
 (35.67,
  'post-office',
  '18.10.2018.',
  'id-card',
  'credit-card',
  'poznan',
  'university',
  'PLN',
  'poland'),
 (10.79,
  'post-office',
  '18.10.2018.',
  'mail',
  'credit-card',
  'poznan',
  'unlabeled',
  'PLN',
  'poland'),
 (2.61,
  'jakdojade',
  '18.10.2018.',
  'tram',
  'credit-card',
  'poznan',
  'transport',
  'PLN',
  'poland'),
 (2.61,
  'jakdojade',
  '18.10.2018.',
  'tram',
  'credit-card',
  'poznan',
  'transport',
  'PLN',
  'poland'),
 (62.38,
  'biedronka',
  '19.10.2018.',
  'food',
  'credit-card',
  'poznan',
  'groceries',
  'PLN',
  'poland'),
 (2.61,
  'jakdojade',
  '19.10.2018.',
  'tram',
  'credit-card',
  'poznan',
  'transport',
  'PLN',
  'poland'),
 (60.81,
  'biedronka',
  '22.10.2018.',
  'food',
  'credit-card',
  'poznan',
  'groceries',
  'PLN',
  'poland'),
 (17.3,
  'beidronka',
  '26.10.2018.',
  'food',
  'cash',
  'poznan',
  'groceries',
  'PLN',
  'poland'),
 (71.21,
  'voyager-katowi',
  '27.10.2018.',
  'bus',
  'credit-card',
  'poznan',
  'travel',
  None,
  None),
 (31.12,
  'cuba-libre',
  '30.10.2018.',
  'alcohol',
  'credit-card',
  'poznan',
  'activities',
  None,
  None),
 (22.46,
  'bp-piast',
  '01.11.2018.',
  'food',
  'credit-card',
  'poznan',
  'groceries',
  None,
  None),
 (121.93,
  'biedronka',
  '02.11.2018.',
  'food',
  'credit-card',
  'poznan',
  'groceries',
  None,
  None),
 (128.07,
  'carrefour',
  '02.11.2018.',
  'food',
  'credit-card',
  'poznan',
  'groceries',
  None,
  None),
 (5.59,
  'adventofcode',
  '03.11.2018.',
  'donation',
  'credit-card',
  'poznan',
  'online',
  None,
  None),
 (34.06,
  'adventofcode',
  '03.11.2018.',
  'donation',
  'credit-card',
  'poznan',
  'online',
  None,
  None),
 (4.43,
  'vending-machine',
  '06.11.2018.',
  'food',
  'credit-card',
  'poznan',
  'fastfood',
  None,
  None),
 (70.93,
  'biedronka',
  '06.11.2018.',
  'food',
  'credit-card',
  'poznan',
  'groceries',
  None,
  None),
 (5.24,
  'vending-machine',
  '08.11.2018.',
  'food',
  'credit-card',
  'poznan',
  'fastfood',
  None,
  None),
 (660.0,
  'dorm',
  '08.11.2018.',
  'accomodation',
  'credit-card',
  'poznan',
  'accomodation',
  None,
  None),
 (155.54,
  'paypal-dbver',
  '08.11.2018.',
  'bus',
  'credit-card',
  'poznan',
  'transport',
  None,
  None),
 (None,
  'burger-king',
  '09.11.2018.',
  'food',
  'credit-card',
  'berlin',
  'fastfood',
  None,
  None),
 (67.41,
  'primark',
  '09.11.2018.',
  'underwear',
  'credit-card',
  'berlin',
  'clothes',
  None,
  'germany'),
 (None,
  'corner-shop',
  '09.11.2018.',
  'gift',
  'credit-card',
  'berlin',
  'gifts',
  None,
  None),
 (None,
  'mcdonalds',
  '09.11.2018.',
  'food',
  'credit-card',
  'berlin',
  'fastfood',
  None,
  None),
 (52.73,
  'edeka',
  '09.11.2018.',
  'food',
  'credit-card',
  'berlin',
  'fastfood',
  None,
  'germany'),
 (None,
  'flixbus',
  '10.11.2018.',
  'bus',
  'credit-card',
  'berlin',
  'travel',
  None,
  None),
 (14.14,
  'KFC',
  '10.11.2018.',
  'food',
  'credit-card',
  'prague',
  'fastfood',
  None,
  'czech'),
 (None,
  'restaurant',
  '10.11.2018.',
  'food',
  'credit-card',
  'prague',
  'fastfood',
  None,
  None),
 (22.29,
  'Billa',
  '10.11.2018.',
  'food',
  'credit-card',
  'prague',
  'groceries',
  None,
  'czech'),
 (None,
  'ecolines',
  '11.11.2018.',
  'bus',
  'credit-card',
  'prague',
  'travel',
  None,
  None),
 (None,
  'war-main-station',
  '11.11.2018.',
  'wc',
  'cash',
  'warszaw',
  'travel',
  None,
  None),
 (None,
  'jakdojade',
  '11.11.2018.',
  'bus',
  'credit-card',
  'warszaw',
  'transport',
  None,
  None),
 (20.57,
  'carrefour',
  '11.11.2018.',
  'food',
  'credit-card',
  'warszaw',
  'groceries',
  None,
  'poland'),
 (None,
  'intercity',
  '11.11.2018.',
  'train',
  'credit-card',
  'warszaw',
  'travel',
  None,
  None),
 (81.32,
  'biedronka',
  '13.11.2018.',
  'food',
  'cash',
  'poznan',
  'groceries',
  None,
  None),
 (70.83,
  'ryanair',
  '14.11.2018.',
  'airplane',
  'credit-card',
  'poznan',
  'travel',
  None,
  None),
 (34.71,
  'sleep-planet',
  '17.11.',
  'supplies',
  'credit-card',
  'poznan',
  'decorations',
  None,
  None),
 (67.54,
  'biedronka',
  '17.11.',
  'food',
  'credit-card',
  'poznan',
  'groceries',
  None,
  None),
 (17.8,
  'elite-cukiern',
  '18.11.',
  'food',
  'credit-card',
  'poznan',
  'groceries',
  None,
  None),
 (103.0,
  'carrefour',
  '20.11.',
  'food',
  'credit-card',
  'poznan',
  'groceries',
  None,
  None),
 (12.19,
  'therms-malta',
  '22.11.',
  'activity',
  'credit-card',
  'poznan',
  'activities',
  None,
  None),
 (17.43,
  'therms-malta',
  '22.11.',
  'activity',
  'credit-card',
  'poznan',
  'activities',
  None,
  None),
 (54.01,
  'biedronka',
  '22.11.',
  'food',
  'credit-card',
  'poznan',
  'groceries',
  None,
  None),
 (128.21,
  'zindo',
  '23.11.',
  'food',
  'credit-card',
  'poznan',
  'fastfood',
  None,
  None),
 (544.17,
  'vans',
  '23.11.',
  'clothes',
  'credit-card',
  'poznan',
  'clothes',
  None,
  None),
 (233.2,
  'flixbus',
  '23.11.',
  'bus',
  'credit-card',
  'poznan',
  'travel',
  None,
  None),
 (191.02,
  'udemy',
  '26.11.',
  'course',
  'credit-card',
  'poznan',
  'online',
  None,
  None),
 (41.0,
  'namecheap',
  '26.11.',
  'domain',
  'credit-card',
  'poznan',
  'online',
  None,
  None),
 (41.49,
  'bakery',
  '28.11.',
  'food',
  'credit-card',
  'poznan',
  'groceries',
  None,
  None),
 (4.04,
  'jakdojade',
  '28.11.',
  'bus',
  'credit-card',
  'poznan',
  'transport',
  None,
  None),
 (69.0,
  'biedronka',
  '28.11.',
  'food',
  'credit-card',
  'poznan',
  'groceries',
  None,
  None),
 (153.0,
  'dorm',
  '28.11.',
  'accomodation',
  'cash',
  'poznan',
  'accomodation',
  None,
  None),
 (18.5,
  'jakdojade',
  '29.11.',
  'tram',
  'cash',
  'poznan',
  'transport',
  None,
  None),
 (40.11,
  'tea-shop',
  '29.11.',
  'food',
  'credit-card',
  'poznan',
  'groceries',
  None,
  None),
 (38.32,
  'rossmann',
  '29.11.',
  'supplies',
  'credit-card',
  'poznan',
  'groceries',
  None,
  None),
 (20.39,
  'biedronka',
  '29.11.',
  'food',
  'credit-card',
  'poznan',
  'groceries',
  None,
  None),
 (34.88,
  'pharmacy',
  '30.11.',
  'supplies',
  'credit-card',
  'poznan',
  'groceries',
  None,
  None),
 (9.0,
  'bauhaus',
  '30.11.',
  'supplies',
  'cash',
  'poznan',
  'groceries',
  None,
  None),
 (20.0,
  'atm',
  '30.11.',
  'withdrawal',
  'credit-card',
  'poznan',
  'bank',
  None,
  None),
 (23.0,
  'christmas-bar',
  '30.11.',
  'alcohol',
  'cash',
  'poznan',
  'activities',
  None,
  None),
 (18.0,
  'christmas-bar',
  '30.11.',
  'food',
  'cash',
  'poznan',
  'fastfood',
  None,
  None),
 (75.0,
  'flixbus',
  '02.12.',
  'bus',
  'credit-card',
  'poznan',
  'travel',
  None,
  None),
 (4.5, 'gdynia-wc', '03.12.', 'wc', 'cash', 'gdynia', 'wc', None, None),
 (9.0,
  'mcdonalds',
  '03.12.',
  'food',
  'credit-card',
  'gdynia',
  'fastfood',
  None,
  None),
 (5.0,
  'pkp-skm',
  '03.11.',
  'train',
  'credit-card',
  'gdynia',
  'travel',
  None,
  None),
 (135.0,
  'intercity',
  '03.11.',
  'train',
  'credit-card',
  'gdynia',
  'travel',
  None,
  None),
 (48.0,
  'bobby-burgers',
  '03.12.',
  'food',
  'credit-card',
  'sopot',
  'fastfood',
  None,
  None),
 (3.5,
  'pkp-skm',
  '03.12.',
  'train',
  'credit-card',
  'sopot',
  'travel',
  None,
  None),
 (8.0,
  'biedronka',
  '03.12.',
  'food',
  'cash',
  'gdansk',
  'groceries',
  None,
  None),
 (130.0,
  'flixbus',
  '03.12.',
  'bus',
  'credit-card',
  'gdansk',
  'travel',
  None,
  None),
 (4.5, 'krakow-wc', '04.12.', 'wc', 'cash', 'krakow', 'wc', None, None),
 (31.5,
  'pizzaeria',
  '04.12.',
  'food',
  'cash',
  'krakow',
  'fastfood',
  None,
  None),
 (51.5,
  'sereno',
  '04.12.',
  'accomodation',
  'cash',
  'krakow',
  'travel',
  None,
  None),
 (103.0, 'flixbus', '05.12.', 'bus', 'cash', 'krakow', 'travel', None, None),
 (69.0,
  'biedronka',
  '05.12.',
  'food',
  'cash',
  'poznan',
  'groceries',
  None,
  None),
 (52.0,
  'multikino',
  '06.12.',
  'cinema',
  'cash',
  'poznan',
  'activities',
  None,
  None),
 (54.0,
  'wood-shop',
  '06.12.',
  'supplies',
  'cash',
  'poznan',
  'groceries',
  None,
  None),
 (16.5,
  'biedronka',
  '06.12.',
  'food',
  'credit-card',
  'poznan',
  'groceries',
  None,
  None),
 (5.0,
  'jakdojade',
  '07.12.',
  'bus',
  'credit-card',
  'poznan',
  'transport',
  None,
  None),
 (21.0,
  'biedronka',
  '07.12.',
  'food',
  'credit-card',
  'poznan',
  'groceries',
  None,
  None),
 (15.0,
  'tiger',
  '07.12.',
  'gifts',
  'credit-card',
  'poznan',
  'gifts',
  None,
  None),
 (665.0,
  'dorm',
  '11.12.',
  'accomodation',
  'credit-card',
  'poznan',
  'accomodation',
  None,
  None),
 (172.0,
  'biedronka',
  '11.12.',
  'food',
  'credit-card',
  'poznan',
  'groceries',
  None,
  None),
 (4.0,
  'jakdojade',
  '13.12.',
  'tram',
  'credit-card',
  'poznan',
  'transport',
  None,
  None),
 (50.0,
  'tiger',
  '15.12.',
  'gifts',
  'credit-card',
  'poznan',
  'gifts',
  None,
  None),
 (74.0,
  'biedronka',
  '15.12.',
  'food',
  'credit-card',
  'poznan',
  'groceries',
  None,
  None),
 (4.0,
  'jakdojade',
  '18.12.',
  'bus',
  'credit-card',
  'poznan',
  'transport',
  None,
  None),
 (17.0,
  'ber-bus',
  '18.12.',
  'bus',
  'credit-card',
  'bergamo',
  'travel',
  None,
  None),
 (11.0,
  'ber-bus',
  '18.12.',
  'bus',
  'credit-card',
  'bergamo',
  'travel',
  None,
  None),
 (41.0,
  'ber-mil-train',
  '18.12.',
  'train',
  'credit-card',
  'bergamo',
  'travel',
  None,
  None),
 (52.0,
  'mcdonalds',
  '18.12.',
  'food',
  'credit-card',
  'milano',
  'fastfood',
  None,
  None),
 (7.0,
  'portello',
  '18.12.',
  'food',
  'credit-card',
  'milano',
  'groceries',
  None,
  None),
 (259.0,
  'flixbus',
  '18.12.',
  'bus',
  'credit-card',
  'milano',
  'travel',
  None,
  None),
 (38.0, 'konzum', '22.12.', 'food', 'cash', 'zagreb', 'groceries', None, None),
 (15.0,
  'ice-skating',
  '23.12.',
  'ice-skating',
  'cash',
  'zagreb',
  'activities',
  None,
  None),
 (15.0,
  'ice-skating',
  '23.12.',
  'ice-skating',
  'cash',
  'zagreb',
  'activities',
  None,
  None),
 (100.0, 'ina', '23.12.', 'gas', 'cash', 'zagreb', 'car', None, None),
 (10.0,
  'konzum',
  '24.12.',
  'food',
  'credit-card',
  'zagreb',
  'groceries',
  None,
  None),
 (100.0, 'ina', '27.12.', 'gas', 'cash', 'zagreb', 'car', None, None),
 (120.0,
  'ice-skating',
  '27.12.',
  'ice-skating',
  'cash',
  'zagreb',
  'activities',
  None,
  None),
 (200.0, 'ina', '27.12.', 'gas', 'cash', 'zagreb', 'car', None, None),
 (12.0,
  'coffee-shop',
  '06.01.2019.',
  'coffee',
  'cash',
  'zagreb',
  'activities',
  None,
  None)]